set nocompatible              " be iMproved, required
filetype off                  " required

set rtp+=~/.vim/bundle/Vundle.vim

call vundle#begin()

Plugin 'VundleVim/Vundle.vim'
Plugin 'vim-airline/vim-airline'
Plugin 'scrooloose/nerdtree'
Plugin 'ervandew/supertab'
Plugin 'airblade/vim-gitgutter'
Plugin 'junegunn/fzf'
Plugin 'ctrlpvim/ctrlp.vim'

call vundle#end()            " required

filetype plugin indent on    " required
" To ignore plugin indent changes, instead use:
"filetype plugin on

"
" Brief help
" :PluginList       - lists configured plugins
" :PluginInstall    - installs plugins; append `!` to update or just :PluginUpdate
" :PluginSearch foo - searches for foo; append `!` to refresh local cache
" :PluginClean      - confirms removal of unused plugins; append `!` to auto-approve removal
"
" see :h vundle for more details or wiki for FAQ
" Put your non-Plugin stuff after this line

"###################"
" Non vundle config "
"###################"

colorscheme iceberg

syntax on

set background=dark
set expandtab tabstop=4 softtabstop=4 shiftwidth=4 smartindent
set noerrorbells
set number
set mouse=a
set backspace=2
set ruler
set hlsearch
set cursorline
set nowrap
set encoding=utf-8
set colorcolumn=80
set incsearch

" Display useless spaces before a /n
autocmd BufWinEnter * let w:m2=matchadd('Tab', '\t', -1)
autocmd BufWinEnter * let w:m3=matchadd('Space', '\s\+$\| \+\ze\t', -1)
highlight Tab ctermbg=NONE guibg=NONE
highlight Space ctermbg=darkred guibg=darkred

" Auto NERDTree without focus
"autocmd vimenter * NERDTree
" Close vim if the only window left open is a NERDTree
autocmd bufenter * if (winnr("$") == 1 && exists("b:NERDTree") && b:NERDTree.isTabTree()) | q | endif

" `gf` opens file under cursor in a new vertical split
nnoremap gf :vertical wincmd f<CR>

